hash-format = "sha256"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "be8add109f8f322fba95c7e6cc85c4c0754dc9a8d41d0528dbb3aadaa002b095"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "b2713b0ea64ce3f114d0712b7c5dbe6da95ce1fd44a1a97494300294231e8bd0"

[[files]]
file = "config/yosbr/config/chatpatches.json"
hash = "fdfa3e488489ad1068fd97cdb3372bcab6f03b74b79f405b32026486d4d9ad04"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "893aec85a0c63123dcb70de5633f70d104e3e2b6a1384206c1aea05fc99d8beb"

[[files]]
file = "config/yosbr/config/inventoryprofilesnext/inventoryprofiles.json"
hash = "e65a2031934b59abcdf8e3682ff4d7029dada5858bca9d4fe054474b896e2726"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "bc5fc249179fa926c9395c63626120f52f55e5c25638712a3e4008a3737e9013"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "98769d10a530e301a95ad1da8a710c8671e93d8be7b921cc614da63f64523fdb"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "c9b7c90236ae7a0b0f2970ecf99f78668ccf355b5c7d50a2c6ba61fa5e74f144"

[[files]]
file = "config/yosbr/config/replaymod.json"
hash = "b0de7bcbab3c360450369bba7d647562c7610c9f11e9fb44bbd1e3fdb8460d08"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "0d5ec9130dd8f8ec24ef6ff740aa48ad286749a7e4746e95397e4b70783b7f2c"

[[files]]
file = "config/yosbr/config/xaerominimap.txt"
hash = "1828085407931efe6c962f0944645b87f41812a7e95e1cd321ccf43217778899"

[[files]]
file = "config/yosbr/config/xaeroworldmap.txt"
hash = "c01659d942f7fd23bbc78d9a2f352e9ce586d9c3fd40cbf59b76fcaed1af9a48"

[[files]]
file = "config/yosbr/options.txt"
hash = "cc01cf0b9bcb648c86b034c83b74453298bca96fae31ff3ab8b1c9e167dbdc37"

[[files]]
file = "mods/accurate-block-placement-reborn.pw.toml"
hash = "29857ebb80e0c8a7cb570ac609b49e7ac3f3262b6dcce93614dd23cda51e7c1d"
metafile = true

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "b4897ff5706d7452917b6f8559210f60ae301c811a042df57df31c989e990b54"
metafile = true

[[files]]
file = "mods/amecs.pw.toml"
hash = "4e28293f194a17008f05bdd638cbf09b02470e78c20cf6ef82d64759f126964f"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "f0463f1b50e2c2ab3c726b14236b22e07ce9be4896528ede9d51486a212a5c07"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
hash = "a250b0920d7b0ef845e257196e09e61b8ea2a66a66c1139fc469bf86dfba24db"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "31da0d40daba6f88d50d18ae5565aee6996657bcc34138f75622dd8f582385f6"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "961a423cc427d4c785354239e8e7b251b5575756b1cf85dd1bc85011b47f0fbf"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "8b13db034aecef8d45addf4f12aa024d35b905ae144df48542683e1b162ba4f9"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "45ef79853a6e968323dadc477f2b68c046948a9e5b2445fed3ab5586598347cf"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "82b20a5c104de33dc01364ff2bf1354132327d085a3dc10954b5ea0ff3d53f51"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "e2c268027d63e997ef750bcbc76e9ee29c775b7121a0be28a121bc4f332a7092"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "c85c3e680af7e30e2379956a67bd8b0f5d424390f7a130f507143ec4984cc6cd"
metafile = true

[[files]]
file = "mods/camera-utils.pw.toml"
hash = "d56937a6cc76dfeefb55f46268783dcb0e1c8fc02abb2f4fca06294bf66a705d"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "617563db0d44229fb65eb660130d02d1a4d2f29233eda03b68d3273e700326f8"
metafile = true

[[files]]
file = "mods/carpet-extra.pw.toml"
hash = "fd2d14a4b440fe1636c220f9f6530a42f79860ecbd5288d30186ac4c7d0f07e5"
metafile = true

[[files]]
file = "mods/carpet-fixes.pw.toml"
hash = "590d03cf3e5e0915028c371ad4f5b7d0ac37b8108f06c242febbdbd131dd56f2"
metafile = true

[[files]]
file = "mods/carpet-tis-addition.pw.toml"
hash = "3d597bb2325fd10e05a12be84f45eff5033bba094d35aade9af9861826f09721"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "a44e6eac50227e4346d507836214f8ec462e74a264307253ec19bd3343ad0c7f"
metafile = true

[[files]]
file = "mods/caxton.pw.toml"
hash = "2faee95f643b08c9e34bd2f5cf402c73947149b5132147b6e2e5ca347a2c96df"
metafile = true

[[files]]
file = "mods/chatpatches.pw.toml"
hash = "56858401a04d2a60d3f7cd26e54be4dc4414b5e439e989733ccd9b8ba7fc7ec2"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "6211df918f9c91638c0e6e56361192afcd60d336b95687e4766540f9d2b6f118"
metafile = true

[[files]]
file = "mods/chunkyborder.pw.toml"
hash = "709554406c3504f85c70f718d3a966839ca0b98d848f3e128879885c11f01631"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "7a4414a95295f22f036699300878058ddf043659fc95ac1bf1d7f725acb0bc46"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "f250d6778f5b8d03ca32913bea5ea677508e9bb6d8201cdebe005bbe9c3100ee"
metafile = true

[[files]]
file = "mods/command-macros.pw.toml"
hash = "45f133fd2c9b1fdb5f21705b201906b3a586dc6ca2d91407fed7ff106a7cfe77"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "951d42cf8154f811de3135952d5f444679946ab7c948e33d87da744679901803"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "1a65361cf2207ba6bad6eba3e66e407983452398c4ac5cbe5db0d8430b8a6496"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "ee965d6f2e0a9cdc31139b0d8a3367eb8db031065a03142534652573626e9787"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "99b1060fa083ca355f35f09fe02ef04832a313cff855de8522fd1766164e0082"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "78eae6c50ce595dc5e41b3be58f84218f614b8934e72d1f22348aa4bfa66f133"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "179d1b7ca85bd3202749e2cc95413daec331dd37dbcf66d07f12a2cd1c0ee397"
metafile = true

[[files]]
file = "mods/emuno.pw.toml"
hash = "8f0c18360533351fff9237b803b1a91fb86cc9b00d56e61f116076e654c9f8e8"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "1c0633f52455c5c6db31b4d926acbbaa0890d771177b55e33eb245a7bc63b635"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "307cd10b6f2fa6aa4731540f76802e8803e8e93e1cc747927ae94bc168cbcbbf"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "1c267253fb20ff2891b75a531cb6c080d39ee416a417a0fc8814abeaed13383b"
metafile = true

[[files]]
file = "mods/extreme_sound_muffler.pw.toml"
hash = "2b4f55d3c73c57155541b281f210fbe85b81c6e15f219b6181e553ecf62a6981"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "07e0e6a791f94db3ff245a16ba014936e35410fe0ee9aba9cbac2deee25f5a70"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "e602bc6bb7b5ca5e4fb2351e285cd715ea5f7a4b4f83ffa6e137319e89e41a68"
metafile = true

[[files]]
file = "mods/fabricskyboxes-interop.pw.toml"
hash = "f80e4a46fab9a9c99ebf3193f2c73675f6f6659fcd740692e14501213f633c70"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "4d979c0f0902b82fc22fc60b741d3a9ce8331de9ffcc4f54658af92ff8ff8a81"
metafile = true

[[files]]
file = "mods/fadeless.pw.toml"
hash = "bd5311680997fada18e6492a91770fdc0762c718b3109820d67c1b019c2f1bf8"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "ff278c8a9a5e56d412fb2e7106790b0ac33b0a4a8699978f0ae4d5a2c70c63b3"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "4146027b92b4885fddec00435233c61c3728b5e09265982ab187021519a4fa89"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "d10d6632f398e4bc8f62555eab1d70a6624837741fc653f2e2a18188166c6477"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "e416b18eebf514dea2014cf5c7fd3ee8493934a0b4e937509f15172ad271fde2"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "f91f449f949d8618e231fa4a64b8715c49d13030779273cfa0b7a5f889b4c0ed"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "9e7bccd0c45b66352abd6fc0b1fa2745d564deb24f5c53dd20728847cf27dda0"
metafile = true

[[files]]
file = "mods/item-scroller.pw.toml"
hash = "55a6e99e45313cb3d8bea34f1d7699bb2f4cbc71ad94ef193af0e98254bc67b0"
metafile = true

[[files]]
file = "mods/itemswapper.pw.toml"
hash = "111846f4c6544ebfe2119d987c2c93d80a21cf3a52451c69681976403c2d8480"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "d398662ae6e9d87e89384ba50a9787dbeb9425902a18b0cd8239efd0b966b453"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "b9749a14f4cc5697124cdbd46c313384713a9c28f4b30a5baae6d43e8561e83c"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "46775cb51714cb624ab336889c25c29945998c67b8f32f8fb11e9fb7ecf50c67"
metafile = true

[[files]]
file = "mods/litematica-printer.pw.toml"
hash = "f3c02f2f5435126ef37b334e159c74ae4003eafba7c703d755931243121fad3e"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "cfe29cfca29dbb7e4d357dfad08cea55146c310bfd41a9c58b2dbcc8ae7fa0b5"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "3dedde5213176d72e1c353877fa44315945e8f3da2ba05f5679d81e9f558bb1d"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "2a79f7fb98b7073c926c6f87a93473f5714cf82a2ace7f344e4e2de4a33e0233"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "d2e031c94440f18885945f97f92e093bbe527d698897f2047daeac166c71d0ff"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "3c0945a312aca06a2185b00cb03ae482949b008d72614497148aa2df301af019"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "052c3feacfce8e544cd4bc8b5abdc2283b9fa774a6993f337dee330d6123baba"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "b89656eaf7e4404d8d2c5b1e1155aae85a839939f83cab6d1b5e791412ad5f86"
metafile = true

[[files]]
file = "mods/moddetectionpreventer.pw.toml"
hash = "afab2fbd384fd1f093b7b6d1500d3227c129223b4a6e2ee62ed43b63bfae8f1d"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "c0daa1b0438a80083fed9145abe9760e6d4b0f5d3f091ea12e893c32072c8899"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "f334786b4fa5a2cb0a6a952fa2a6ab74de3395c2be806045ea3a5905edd75363"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "979e6d73369f2e45666e49c387f7f4f9b266df1085d4a7a949039aac461b3c13"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "a6a57004f5990ae59be0b89eb2edc5f50e2233d0410bd5f8060d58401592e0ef"
metafile = true

[[files]]
file = "mods/no-night-vision-flickering.pw.toml"
hash = "4f818e0cf25d689e726ac5b6ff3b95c65db03046beb447981a9d049ec388d30b"
metafile = true

[[files]]
file = "mods/no-resource-pack-warnings.pw.toml"
hash = "c8df23a6f0bd41d2f562b460e94bb3df7df1932298bf7b5081e43dfd7c270fae"
metafile = true

[[files]]
file = "mods/nvidium.pw.toml"
hash = "07dd8775324c01058896b4572e23a1ca1c355186cc501c61fc68e1151c5e177c"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "b2db81b53e71fc73306a4a5bafb7a33662e2e3da6d77210db607466cd4c41d49"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "98f25d8c648b5872bab1d59f0ea4acbca07e086af6fb5ff32422d354579cfd91"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "0e59d00de821ce2095849c161e17e03d12a768d18859e813086adeaa71fd037b"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "975478c93b1218131fd48695cd7efb9bbe0d69125409940b015a7058e42fb6be"
metafile = true

[[files]]
file = "mods/replay-voice-chat.pw.toml"
hash = "6a3ebc6365a4b7f51025dabf2c686dc588abc1e4048242a6d06a6f38d353156e"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "89d0605e73d81cd1d346e84fcb0daa37169f3aa61e95e306462f4581def43912"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "c16e5515c9578fb21ede824ddc04c155687e64f905501648120b89f7669d57d1"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "b45be2af8beef3e632a89482ca4a11028d89bc063ca282c112ee69e886992d43"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "f7c09e537f9db67804dd7df6b8ba3a0cfb63429ad992a99e8f8faba33187ded2"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "71164245f9e06a916689d4683bd15dec40effbb1a748e353318c243bbee4924e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "5e73967368d47038c38dc52fa298b45603fbe6baf2608f171638ff767178ad9a"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "3f1cdc39c7c76eba1c62b6f22d07f9507ff1c9a9e860f179481ec63449451a79"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "c190e3b4f36f65c9c6ce72beb5f9760fa9c3793be2fa956e09d99fbbaeef6aaa"
metafile = true

[[files]]
file = "mods/syncmatica.pw.toml"
hash = "b8686f7382b6667de82d37b7f0ef8a33955b6ee65231d0178fb78d6eb14bf5a5"
metafile = true

[[files]]
file = "mods/tellme.pw.toml"
hash = "98301f15b45a725cd13710053b98e8f6e5bb15ee484e0f1deadde5fa3fc27f22"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
hash = "d547b13c44aa82e00e2ec1a1cb2c12acc38e84d5a771c7912f88a832213b1a76"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "cd55d6298c52f17e360d2166ca5a7fc23083118f761deca96f23f6e90d40a314"
metafile = true

[[files]]
file = "mods/worldedit-cui.pw.toml"
hash = "68557e8b0cd7bdf1015c3760d70841a876284d7f83b36bfea022a8612e8a393a"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "e8e60c63af40fc61446877e68a7a3a674f61e3fcd02293e813d33eb5977c4e36"
metafile = true

[[files]]
file = "mods/xaeroplus.pw.toml"
hash = "0d17ca89d0f1f0a39dd7bdace90a671f2fbd602f6faf015637657ec6774bc035"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "868925f9646189c9d395ee0a1c3672e031e9261f91273d666f47d5e080e968c7"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "e92e0c8f73b049649c18fc8a5f2e9a7fe310ed6cec310811399db51b99a2b715"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f2c750d280102a311769d802f9b151f5d6850c04a8cba6090a2e802de54ff6ce"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
hash = "6ba173154c8fe78d78524902a420006e0f1af92533d990fc36d14e55f33327b4"
metafile = true

[[files]]
file = "resourcepacks/fast-better-grass.pw.toml"
hash = "2d9ab5d76c32219c684dbb599ef9ebc6d99148a084c38bc61c0cf1ea5f16a77c"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
hash = "2b28d0ac540b0c498003fc24f7724c8ed03798728be55a6feb22c689eb2d04fb"
metafile = true

[[files]]
file = "resourcepacks/xk-redstone-display.pw.toml"
hash = "543bcafcd56efc6a9d191f3d84749f49d8a627c87455e1939c3e31ae0494b617"
metafile = true
